### ISSUE TITLE
Incorrect mapping

### ISSUE THREAD

**Issue by williewheeler-ms** [JayKrishnareddy/CleanArchitecture#1]
The builder configures `FirstName` twice and doesn't configure `LastName`:
https://github.com/JayKrishnareddy/CleanArchitecture/blob/6ea0a8d097392c9e5c73d44f1361eff620820425/DataAccessLayer/EntityMappers/UserMap.cs#L22

**Comment by JayKrishnareddy** [comment]
Thank u Willie 
I will modify this asap

**Comment by JayKrishnareddy** [comment]
Mapping configured with correct property name
